### PR TITLE
Added support for G815

### PR DESCRIPTION
**Pull request by cornernote**
It was a bit different to the other keyboards, so some core changes were needed.

### CODE REVIEW

**Comment by cornernote** [comment]
NOT READY YET - I have to test and then squish, sorry for the PR before it's ready...

**Comment by cornernote** [comment]
@tolga9009 I think this PR is ready. It works for me, and the code seems reasonably clean, however I'd like someone to look over it.  I'm not a C++ programmer, and all this jazz with declaring types and pointers was a bit tricky.

Basically the keyboard is sent commands from the software in 20 byte buffers, rather than the other keyboards which use feature get/set.

You can see this in a python script here: https://gist.github.com/cornernote/82972cc307985df29f3ddca214a4dc39#file-g815-led-py-L47

I implemented it like this for keyboard init -  https://github.com/cornernote/sidewinderd/blob/master/src/vendor/logitech/g815.cpp#L151 

and like this for the on/off LED control - https://github.com/cornernote/sidewinderd/blob/master/src/core/led.cpp#L13 and https://github.com/cornernote/sidewinderd/blob/master/src/core/hid_interface.cpp#L48

I also needed to add a new key type, because otherwise MR and M1 were detected as the same key.

Would also like to say thank you for making this project.  I have used it for years with my G105, and now I have a G815 it's allowed me to learn new things including with wireshark and c++.

**Comment by tolga9009** [comment]
Thanks for your efforts! I've only looked over the PR - haven't built, nor tested yet. Let me get it clear first: I'm very positive towards your patch and will merge it, but we need to rework some parts of it:

1. Looking at file `src/vendor/logitech/g815.cpp`, `G815_FEATURE_REPORT_LED = 0` doesn't seem correct to me. Looking further, you seem to circumvent this by adding new functions to various core components for writing to HID. However, we already have `HidInterface::setReport()`. By no means I'm saying `HidInterface` is good or complete, but it looks like `HidInterface::writeData()` is redundant.

    Can you share your USB captures / reverse engineering notes? I'm sure the needed information can be found there.

2. In file `src/core/key.hpp`, you have added a new `KeyType::Record`. We can discuss for adding it in another patch for all keyboards, but it shouldn't be in the scope of this patch.

3. `LogitechG815::resetMacroKeys()` also looks incorrect to me. You're not using HID Feature Report function, but writing directly to the fd (twice?!). We are doing this on other Logitech keyboards, because G1 - G6 are outputting numbers "1" - "6". What's the default behavior on the G815, when you're not using any drivers / sidewinderd? Either way, USB captures would help here aswell.

4. Optimally, your patch should only touch 4 files (e.g. https://github.com/tolga9009/sidewinderd/commit/a0b78ada6056f985ea94d672e8c58bca776710b1):
* `src/core/device.hpp`
* `src/core/device_manager.cpp`
* `src/vendor/logitech/g815.cpp`
* `src/vendor/logitech/g815.cpp`

    Everything outside those files, needs to be critically thought through. LED functions surely need a complete overhaul, especially regarding we have RGB backlit keyboards now, but it's not within the scope of this patch.

So, I think the next step is to review your USB captures / reverse engineering notes. If you need assistance, please let me know.

Again, thanks for all your efforts!

Cheers,
Tolga

**Comment by cornernote** [comment]
@tolga9009 Thanks for your reply.  Are you available, and is there a place we can chat in realtime?

My notes are here:
https://gist.github.com/cornernote/82972cc307985df29f3ddca214a4dc39

My dumps are here:
https://github.com/cornernote/g815-wireshark

**Comment by cornernote** [comment]
I joined here - https://gitter.im/tolga9009/sidewinderd

**Comment by cornernote** [comment]
1.

It seems `setReport()` is different from `writeData`, however I don't really understand what's happening under the hood, I just know I got it working with `write()` and couldn't get it working with `ioctl()`. 
- `setReport()` calls `ioctl(*fd_, HIDIOCSFEATURE(sizeof(buf)), buf);`
- `writeData()` calls ` write(*fd_, buf, size);`

In file `src/vendor/logitech/g815.cpp`, `G815_FEATURE_REPORT_LED = 0` - this is needed to prevent the `setReport()` from being called by `Led::on()` and `Led::off()`, and it instead calls `writeData()`.  

If we can get it working with a call to `ioctl(*fd_, HIDIOCSFEATURE(sizeof(buf)), buf)` then this would not be needed.

2. 

`KeyType::Record` was needed because these keys are the same:
- `constexpr auto G815_KEY_M1 = 0x01;` - comes in to `getInput()` as `0x11 0xff 0x0b 0x00 0x01`
- `constexpr auto G815_KEY_MR = 0x01;` - comes in to `getInput()` as `0x11 0xff 0x0c 0x00 0x01`

Note the only difference is `buf[2]` (`0x0b` vs `0x0c`).

I am using `buf[4]` as the `key`.  If I set that into `keyData.index = key;`, then M1 and M3 are the same key. I added `KeyType::Record` so that I can set `keyData.type = KeyData::KeyType::Record;` and therefore see the difference.

I understand this may not be part of this commit, however unless there is another way to do it, this may be a prerequisite of this commit.  If this is the case I can do a PR the other keyboards and add this change on it's own.


3. 

At the point of constructing `LogitechG815` there is no HID interface (I think?).

You do the same in `g105.cpp` with `ioctl(fd_, HIDIOCSFEATURE(sizeof(buf)), buf);`.  I just swapped `ioctl()` to `write()`.  There are 2 calls because the keyboard needs 2 commands to init.
- `11ff111b02000000000000000000000000000000` - run this before enable/disable m-keys, keyboard goes black after running
- `11ff0a2b01000000000000000000000000000000` - enable m-keys


4. 

I was thinking the same thing, however as this keyboard is different, and as I'm not a c++ programmer, I decided to submit it as is.  Thank you for your help, and I look forward to working together to make a cleaner PR.

**Comment by cornernote** [comment]
Regarding #2, I realised I can do this without changing any other files if I set `keyData=key = buf[2]` for MR, and keep using `buf[4]` for the other keys.

I put it in a new branch:
https://github.com/tolga9009/sidewinderd/compare/master...cornernote:g815-support?expand=1

I still changed the files to do with the HID Interface.  We can talk more about how to handle that once you have seen my notes and wireshark dumps.

**Comment by cornernote** [comment]
Regarding (1), It's also worth noting, I was using this file as a reference:
https://github.com/signal11/hidapi/blob/master/linux/hid.c

`hid_send_feature_report()` vs `hid_write()`

I found that because MatMoul/g810-led uses it to send instructions to similar keyboards: https://github.com/MatMoul/g810-led/blob/master/src/classes/Keyboard.cpp#L799

**Comment by tolga9009** [comment]
2: There are multiple ways to solve it, but for now, this one should do: define `G815_KEY_MR` as `0x04`. That's totally fine, since it's just for our internal representation and there is overlapping otherwise. [Here](https://github.com/cornernote/sidewinderd/commit/8a2adffe10490ff9c0a6c2aa810b20959730a732#diff-d94c7a0c865a6a5fe9a7f857c180c8a0R109), you can then do `keyData.index = G815_KEY_MR`. Undo everything involving `KeyType::Record`.

1 & 3: How did you capture the traffic? Are you running Windows natively and capturing using Wireshark & USBPcap or are you running Linux & usbmon (Windows in VM, USB pass-through)?

The reason packets look very different in comparison to other keyboards, could be you're using a different Report ID for communication. E.g. the Logitech G710 has Report ID `0x05`, which is long and convoluted aswell; with various key, backlight and LED states and therefore difficult to interface with. However, there are also Report IDs, which are shorter and easier to interface and we're using them instead.

In order to find it out for the G815, I need you to give me the following extra information:
* Output of `sudo lsusb -v -d 046d:c33f`
* Report Descriptors (should be 2, could be more). Use this as a guide: https://github.com/GSeriesDev/gseries-tools/blob/master/CONTRIBUTING.md
* Also, try out usbmon on Linux (as described in the guide above), without running sidewinderd and examine the output of `cat /sys/kernel/debug/usb/usbmon/<BUS>u`. Do you still get something like `0x11 0xff 0x0a ...` when pressing G-Keys, or does it look much simpler now, e.g. `0x03 0x00 0x01`? No need to post the full output here, a short feedback is enough. **Important:** if there are multiple devices on the same bus, append ` | grep 2:004` to the command above, if your keyboard is listed under Bus 002 as Device 004 (`lsusb`).

**Comment by cornernote** [comment]
I'm a bit stuck.  I don't seem to have permission, even as root:

```
# service sidewinderd stop

# mount -t debugfs none /sys/kernel/debug
mount: /sys/kernel/debug: none already mounted or mount point busy.

# ls -la /sys/kernel/debug/hid/ 
total 0
drwxr-xr-x 11 root root 0 Jan 11 12:33 .
drwx------ 39 root root 0 Jan 11 12:33 ..
drwxr-xr-x  2 root root 0 Jan 11 12:33 0003:046D:406A.0008
drwxr-xr-x  2 root root 0 Jan 11 12:33 0003:046D:C248.0006
drwxr-xr-x  2 root root 0 Jan 11 12:33 0003:046D:C248.0007
drwxr-xr-x  2 root root 0 Jan 11 12:33 0003:046D:C33F.0004
drwxr-xr-x  2 root root 0 Jan 11 12:33 0003:046D:C33F.0005
drwxr-xr-x  2 root root 0 Jan 11 12:33 0003:046D:C52B.0001
drwxr-xr-x  2 root root 0 Jan 11 12:33 0003:046D:C52B.0002
drwxr-xr-x  2 root root 0 Jan 11 12:33 0003:046D:C52B.0003
drwxr-xr-x  2 root root 0 Jan 11 12:33 0018:04F3:3091.0009

# cat /sys/kernel/debug/hid/0003\:046D\:C248.0006/rdesc 
cat: '/sys/kernel/debug/hid/0003:046D:C248.0006/rdesc': Operation not permitted

# cat /sys/kernel/debug/hid/0003\:046D\:C33F.0004/rdesc 
cat: '/sys/kernel/debug/hid/0003:046D:C33F.0004/rdesc': Operation not permitted
```

**Comment by cornernote** [comment]
Nevermind, turns out I needed to disable secure boot in my bios.

**Comment by cornernote** [comment]
All gseries-tools dumps have been added here:
https://github.com/cornernote/gseries-tools/tree/master/g815/info

This is a much cleaner way to do it!  I was using wireshark.  Saving the data in nice chunks like this was impossible. I'll have a look at the data compared to the G105.

**Comment by tolga9009** [comment]
Alright, I've done some further reading and thinking.

First of all, `ioctl()` vs `write()`. hidraw kernel docs say, there is no difference for our use case:
```
write()
--------
The write() function will write a report to the device. For USB devices, if
the device has an INTERRUPT OUT endpoint, the report will be sent on that
endpoint. If it does not, the report will be sent over the control endpoint,
using a SET_REPORT transfer.

The first byte** of the buffer passed to write() should be set to the report
number.  If the device does not use numbered reports, the first byte should
be set to 0. The report data itself should begin at the second byte.
```

```
ioctl()
--------
[...] HIDIOCSFEATURE(len): Send a Feature Report
This ioctl will send a feature report to the device.  Per the HID
specification, feature reports are always sent using the control endpoint.
Set the first byte of the supplied buffer to the report number.  For devices
which do not use numbered reports, set the first byte to 0. The report data
begins in the second byte. Make sure to set len accordingly, to one more
than the length of the report (to account for the report number).
```
Primary reason was a better portability for hiddev interface, which only allows `read()` and `ioctl`, but no `write()`. Either way, the issue is not really `ioctl()` vs `write()`, but rather my poorly designed `HidInterface::setReport()`. At the moment, it only allows fixed `buf[2]` rather than a flexible buffer size. Same for `getReport()`.

Just to make sure, try out the following:

```
void LogitechG815::resetMacroKeys() {
	static unsigned char buf1[G815_BUF_SIZE] = {0x11, 0xff, 0x11, 0x1b, 0x02};
	static unsigned char buf2[G815_BUF_SIZE] = {0x11, 0xff, 0x0a, 0x2b, 0x01};

        ioctl(fd_, HIDIOCSFEATURE(sizeof(buf1)), buf1);
        ioctl(fd_, HIDIOCSFEATURE(sizeof(buf2)), buf2);
}
```
If it doesn't work, try this instead:
```
void LogitechG815::resetMacroKeys() {
        static unsigned char buf1[21] = {0x00, 0x11, 0xff, 0x11, 0x1b, 0x02};
        static unsigned char buf2[21] = {0x00, 0x11, 0xff, 0x0a, 0x2b, 0x01};

        ioctl(fd_, HIDIOCSFEATURE(sizeof(buf1)), buf1);
        ioctl(fd_, HIDIOCSFEATURE(sizeof(buf2)), buf2);
}
```
Also for testing purposes, try to enable M3 LED with `ioctl()` in `resetMacroKeys()`:
```
void LogitechG815::resetMacroKeys() {
        [...]
        static unsigned char buf3[G815_BUF_SIZE] = {0x11, 0xff, 0x0b, 0x1c, 0x01};
        ioctl(fd_, HIDIOCSFEATURE(sizeof(buf3)), buf3);
}
```
Again, if it doesn't work, try this instead:
```
void LogitechG815::resetMacroKeys() {
        [...]
        static unsigned char buf3[21] = {0x00, 0x11, 0xff, 0x0b, 0x1c, 0x01};
        ioctl(fd_, HIDIOCSFEATURE(sizeof(buf3)), buf3);
}
```
In the meantime, I will create patches for `HidInterface::setReport()` and `getReport()`.

Cheers,
Tolga

**Comment by cornernote** [comment]
Hey @tolga9009 

I'm in way over my head here, but I'll do my best to try everything out so that we can get a clean and stable merge.

It seems that the `write()` in my `resetMacroKeys()` was not actually working.  I am also running `g810-led`, and that was triggering the reset.  When I removed that it stopped working.  The sidewinderd is correctly doing the leds, but not the init stuff.

`cat /sys/kernel/debug/usb/usbmon/1u` reveals the following:

sidewinderd `ioctl()` - not working:

```
ffff9f9117956480 3789757649 S Co:1:003:0 s 21 09 0311 0001 0014 20 = 11ff111b 02000000 00000000 00000000 00000000
ffff9f9117956480 3789757792 C Co:1:003:0 -32 0
ffff9f9117956480 3789757831 S Co:1:003:0 s 21 09 0311 0001 0014 20 = 11ff0a2b 01000000 00000000 00000000 00000000
ffff9f9117956480 3789757949 C Co:1:003:0 -32 0
```


sidewinderd `write()` - not working:
```
ffff9f91357c9300 34689790 S Co:1:007:0 s 21 09 0211 0001 0014 20 = 11ff111b 02000000 00000000 00000000 00000000
ffff9f91357c9300 34689967 C Co:1:007:0 0 20 >
ffff9f91357c9300 34689988 S Co:1:007:0 s 21 09 0211 0001 0014 20 = 11ff0a2b 01000000 00000000 00000000 00000000
ffff9f91357c9300 34690180 C Co:1:007:0 0 20 >
```


g810-led - `hid_write()` - working [source](https://github.com/MatMoul/g810-led/blob/master/src/classes/Keyboard.cpp#L794):

```
ffff9f93db082540 660536967 C Ii:1:002:3 0:2 7 = 10014903 044c00
ffff9f93db082540 660536997 S Ii:1:002:3 -115:2 32 <
ffff9f92496c2d80 662998327 S Co:1:009:0 s 21 09 0211 0000 0014 20 = 11ff111b 02020000 00000000 00000000 00000000
ffff9f92496c2d80 662998564 C Co:1:009:0 0 20 >
ffff9f93d33d7a80 663000964 C Ii:1:009:2 0:1 20 = 11ff111b 00000000 00000000 00000000 00000000
ffff9f93d33d7a80 663000973 S Ii:1:009:2 -115:1 64 <
ffff9f93d33d7a80 663001961 C Ii:1:009:2 0:1 9 = 02000000 00000000 00
ffff9f93d33d7a80 663001970 S Ii:1:009:2 -115:1 64 <
ffff9f93d33d7a80 663002965 C Ii:1:009:2 0:1 9 = 01000000 00000000 00
ffff9f93d33d7a80 663002971 S Ii:1:009:2 -115:1 64 <
ffff9f93d33d7a80 663003923 C Ii:1:009:2 0:1 5 = 03000000 00
ffff9f93d33d7a80 663003930 S Ii:1:009:2 -115:1 64 <
```

**Comment by cornernote** [comment]
I updated my last comment, simplifying with it for 1 USB command, and including source code so we can see which code outputs which log.

**Comment by tolga9009** [comment]
Hmmm, it's really confusing me, as the packets keep changing. I think we're at a point, where it makes more sense to port over hidpp10 and hidpp20 from libratbag and get it done **right**, rather than try to have a "magic" temporary solution. Luckily, I own a G700, which uses hidpp10 - eventhough it's a mouse, not keyboard. Still, it will be enough to get hidpp10 working in sidewinderd.
 
While trying to understand the packet structure, I've also come across this kernel code: https://github.com/torvalds/linux/blob/master/drivers/hid/hid-logitech-hidpp.c
I think it's perfect for getting more insight into hidpp10/20.

Also while working on `HidInterface`, I've stumbled across hidapi beeing maintained by libusb now (since June 2019). Back then, I chose not to use hidapi due to uncertain maintenance. But beeing backed and maintained by libusb now, I think hidapi is a perfect candidate.

That beeing said, hidpp10 / hidpp20 and hidapi won't be here by tomorrow. As already mentioned, I strongly suggest trying out libratbag, so you have a working solution right now, until we have a working solution here.

**Comment by cornernote** [comment]
I'm glad I'm not the only one confused by all this.  :)

https://github.com/torvalds/linux/blob/master/drivers/hid/hid-logitech-hidpp.c - seems to describe the 2 types of reports being used. It's a lot of code tho. Are you thinking of using it, or just copying key parts from it?

The g810-led software uses hidapi.  I was going to use hidapi instead of my `reportWrite()`, however I wasn't sure how to include it in your cmake/makefile, so making a new function was easier.

I have a working solution.  I init (enable G-Keys) with g810-led, then the rest of the sidewinderd works fine. The current mission is to make the init code work correctly, and make it all clean enough to merge a PR, although there is no rush. I'd rather take the time and understand this and get it right.

I'll await to see how you would like to proceed

**Comment by cornernote** [comment]
@tolga9009 , I just got a new system and plugged in my keyboard, and your version doesn't work.  I checked the logs and I can't see this patch ever being committed.  For now I'll use my branch, but it would be great to see this keyboard added.

**Pull request closed without merging**
