### PR TITLE
Added support for Logitech G105 (Very ugly code duplication)

### PR DESCRIPTION
**Pull request by ntzrmtthihu777**
Greets. It works, but the new code is pretty much 99% a copy of the G710 code.

### CODE REVIEW

**Comment by tolga9009** [comment]
Hi there and thank you for your patch! It looks good to me!

In the process of spreading the word about sidewinderd, I want to stream the whole process of reverse engineering the G105. I'm gonna merge your pull request during my stream, so I can show the people how the workflow works. Expect it to get merged within the next 12 hours.

Thank you!

Cheers,
Tolga

**Comment by ntzrmtthihu777** [comment]
Oh that's cool, are you going to stick the video somewhere us slow internet peons can watch?

**Comment by tolga9009** [comment]
I'm gonna stream it to Twitch and upload it later on YouTube ;).

**Comment by ntzrmtthihu777** [comment]
that would be great, indeed :+1:

**Comment by ntzrmtthihu777** [comment]
Hey, you online and available for chat?

**Comment by tolga9009** [comment]
Hi there, I've created a chat room here: https://gitter.im/tolga9009/sidewinderd. Let's chat there.

**Comment by ntzrmtthihu777** [comment]
Alright, I'm there whenever you are :+1:

**Pull request merged**
